-- Schema Definition for Notes Application

-- 1. Create Table
create table if not exists notes (
  id bigint primary key generated by default as identity,
  title text not null,
  content text,
  is_public boolean default false,
  user_id uuid references auth.users default auth.uid(),
  created_at timestamptz default now(),
  modified_at timestamptz default now()
);

-- 2. Enable Row Level Security
alter table notes enable row level security;

-- 3. Policies

-- View: Public notes OR Own notes
create policy "Public notes are viewable by everyone."
  on notes for select
  using ( is_public = true );

create policy "Users can view their own notes."
  on notes for select
  using ( auth.uid() = user_id );

-- Insert: Authenticated users can create notes
create policy "Users can insert their own notes."
  on notes for insert
  with check ( auth.uid() = user_id );

-- Update: Users can update their own notes
create policy "Users can update their own notes."
  on notes for update
  using ( auth.uid() = user_id );

-- Delete: Users can delete their own notes
create policy "Users can delete their own notes."
  on notes for delete
  using ( auth.uid() = user_id );
